### ISSUE TITLE
Return a set of well defined errors from `validateCovidPassport`

### ISSUE THREAD

**Issue by noway** [CovidEngine/nzcp-js#6]
Currently Will is just returning false if a check fails.

For example in the spec it says

`Check if the payload received from the QR Code begins with the prefix NZCP:/, if it does not then fail.`

We should do something like

`return { success: false, code: 100, message: "Payload must begin with \"NZCP:/\""}`

**Comment by J-eld** [comment]
Hey, I'd like to work on this

**Comment by wseagar** [comment]
We're happy with the structure we landed on and now are just working though the spec.
